baseURL = "https://pride.codes/"
languageCode = "en-us"
title = "pride.codes"

theme = "pride-codes"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-106326008-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Proudly celebrating engineering diversity."
  copyright = ""
  sidebarAbout = [
    "pride.codes provides a collection of simple widgets for businesses to add to their sites. We want businesses to actively show their support for their LGBTQI+ colleagues.",
    "We want businesses to 'fly the flag'.",
  ]
  email = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Privacy statement"
  url = "privacy-statement"

  # [[params.navlinks]]
  # name = "Get in touch"
  # url = "contact/"

  [params.social]
  twitter       = "https://twitter.com/pridecodes"
  github        = "https://github.com/devjack/pride.codes"

[[params.meta]]
    property="og:type"
    content="article"
[[params.meta]]
    property="og:title"
    content="pride.codes"
[[params.meta]]
    property="og:site_name"
    content="pride.codes"
[[params.meta]]
    property="og:description"
    content="Helping to 'fly the flag' and show their support for  LGBTQI+ friends and colleagues."
[[params.meta]]
    property="og:url"
    content="https://pride.codes"
[[params.meta]]
    property="og:image"
    content="https://cdn.pride.codes/img/logo_png_small.png"
[[params.meta]]
    property="article:published_time"
    content="2017-09-12"
[[params.meta]]
    property="article:author"
    content="https://www.twitter.com/developerjack"
[[params.meta]]
    property="article:author"
    content="https://www.twitter.com/_patmurray"
